name: PHP CI with Composer

on: [push]

jobs:
  build:
      strategy:
        fail-fast: false
        # max-parallel: 1
        matrix:
          php-versions: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2']
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup php for mock server
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.2'

        - name: Setup build-in server
          run: |
            nohup php -S localhost:9000 -t ./tests/mock-server/ > phpd.log 2>&1 &
            echo $! > mock-server.pid

        - name: Setup php
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php-versions }}

        - name: Install dependencies
          run: |
            composer self-update
            composer install --no-interaction --prefer-source --dev

        - name: Run cases
          run: |
            ./vendor/bin/phpunit
            cat mock-server.pid | xargs kill

        - name: Print mock servion log
          if: ${{ failure() }}
          run: |
            cat phpd.log


